name: cross(musl)
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master
jobs:
  build_cross:
    name: cross(musl)
    strategy:
      matrix:
        os: [ubuntu-latest]
        cross: [arm-linux-musleabi, aarch64-linux-musl]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Installation
        run: |
          wget https://github.com/xmake-mirror/musl.cc/releases/download/20210202/${{ matrix.cross }}-cross.linux.tgz
          tar -xvf ${{ matrix.cross }}-cross.linux.tgz

      - name: build in cross
        run: |
          xmake f -p cross --toolchain=muslcc --sdk=`pwd`/${{ matrix.cross }}-cross
          xmake