name: linux
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:
  build_debug:
    name: debug
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build in debug
        run: |
          xmake config -m debug
          xmake build

  build_mock:
    name: mock
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    needs: build_debug
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build in debug
        run: |
          xmake config -m debug
          xmake build mock
          xmake r mock
              
  build_dfx:
    name: dfx
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    needs: build_debug
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build in dfx
        run: |
          xmake config -m release
          xmake build unit_test
          xmake r unit_test
        run: |
          xmake build meta
          xmake r meta
          
  build_bench:
    name: bench
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    needs: build_debug

    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build in bench
        run: |
          xmake config -m release
          xmake build bench
          xmake r bench

  build_install:
    name: install
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    needs: [build_bench, build_dfx]

    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: install
        run: |
          xmake config -m release
          xmake
          xmake install -o ./output
          tree ./output
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-coverage-report
      #     path: output/test_linux/code-coverage.html