name: atom with xmake
on:
  push:
    branches:    
      - master

jobs:
  build_linux:
    name: build_and_test in linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # You may pin to the exact commit or the version.
      # uses: xmake-io/github-action-setup-xmake@9b727acdccf5e41bdf2712934983855d8ce146de
      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          # The version to use. Should be a semver range or 'latest'. Or use [{repository}#]branch@{branch_name} to select a branch.
          xmake-version: latest
      - run: |
          xmake config -m debug
          xmake build
          xmake build mock; xmake r mock
      - run: |
          xmake config -m relase
          xmake
          xmake build unit_test
          xmake build bench
          xmake build meta
          xmake r unit_test
          xmake r bench
          xmake r meta
      - run: |
          xmake install -a
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test_linux/code-coverage.html

build_windows:
  name: build_and_test in windows
  runs-on: windows-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # You may pin to the exact commit or the version.
    # uses: xmake-io/github-action-setup-xmake@9b727acdccf5e41bdf2712934983855d8ce146de
    - name: use xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        # The version to use. Should be a semver range or 'latest'. Or use [{repository}#]branch@{branch_name} to select a branch.
        xmake-version: latest
    - run: |
        xmake config -m debug
        xmake build
        xmake build mock; xmake r mock
    - run: |
        xmake config -m relase
        xmake
        xmake build unit_test
        xmake build bench
        xmake build meta
        xmake r unit_test
        xmake r bench
        xmake r meta
    - run: |
        xmake install -a
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: output/test_windows/code-coverage.html

build_unix:
  name: build_and_test in windows
  runs-on: macos-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # You may pin to the exact commit or the version.
    # uses: xmake-io/github-action-setup-xmake@9b727acdccf5e41bdf2712934983855d8ce146de
    - name: use xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        # The version to use. Should be a semver range or 'latest'. Or use [{repository}#]branch@{branch_name} to select a branch.
        xmake-version: latest
    - run: |
        xmake config -m debug
        xmake build
        xmake build mock; xmake r mock
    - run: |
        xmake config -m relase
        xmake
        xmake build unit_test
        xmake build bench
        xmake build meta
        xmake r unit_test
        xmake r bench
        xmake r meta
    - run: |
        xmake install -a
    - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test_unix/code-coverage.html