name: windows
on:
  push:
    branches:    
      - master

  pull_request:
    branches:
      - master

jobs:
  build_mock:
    name: mock
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build in debug
        run: |
          xmake config -m debug ${{ matrix.arch }}
          xmake build mock
          xmake r mock
              
  build_dfx:
    name: dfx
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    needs: build_mock
    steps:
      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: build in dfx
        run: |
          xmake config -m relase ${{ matrix.arch }}
          xmake build unit_test
          xmake r unit_test
          xmake build bench
          xmake r bench
          xmake build meta
          xmake r meta

  build_debug:
    name: debug
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    needs: [build_mock, build_dfx]

    steps:
      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build in debug
        run: |
          xmake config -m debug ${{ matrix.arch }}
          xmake build

  build_install:
    name: install
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    needs: build_debug

    steps:
      - name: use xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: install
        run: |
          xmake config -m relase ${{ matrix.arch }}
          xmake
          xmake install -a
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-coverage-report
      #     path: output/test_linux/code-coverage.html